require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - debug.rb
    - 'spec/approvals/**/*'
    - 'dev/**/*'

# FIXME: Allow longer example in this test code
RSpec/ExampleLength:
  Exclude:
    - spec/menu_commander/examples_spec.rb

# FIXME: Allow `*_any_instance_of` in this test code
RSpec/AnyInstance:
  Exclude:
    - spec/menu_commander/examples_spec.rb
